{% set name = 'bob.pad.base' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - spoof.py         = bob.pad.base.script.spoof:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - "{{ PYTHON }} setup.py sdist --formats=zip"
    {% endif %}
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob.extension
    - bob.io.base
    - bob.pipelines
    - bob.measure
    - bob.bio.base
    - click {{ click }}
    - click-plugins {{ click_plugins }}
    - dask {{ dask }}
    - matplotlib {{ matplotlib }}
    - numpy {{ numpy }}
    - scikit-learn {{ scikit_learn }}
    - scipy {{ scipy }}
    - sqlalchemy {{ sqlalchemy }}
    - tabulate {{ tabulate }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('click') }}
    - {{ pin_compatible('click-plugins') }}
    - {{ pin_compatible('dask') }}
    - {{ pin_compatible('matplotlib') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scikit-learn', min_pin='x.x') }}
    - {{ pin_compatible('scipy') }}
    - {{ pin_compatible('sqlalchemy') }}
    - {{ pin_compatible('tabulate') }}

test:
  imports:
    - {{ name }}
  commands:
    - bob pad --help
    - pytest --verbose --cov {{ name }} --cov-report term-missing --cov-report html:{{ project_dir }}/sphinx/coverage --cov-report xml:{{ project_dir }}/coverage.xml --pyargs {{ name }} sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: A framework for executing the chain of presentation attack detection (PAD) experiments
  license_family: GPL
