{% set name = 'bob.pad.base' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - spoof.py         = bob.pad.base.script.spoof:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.db.base
    - bob.io.base
    - bob.bio.base
    - bob.bio.video
    - bob.bio.gmm
    - bob.learn.linear
    - bob.learn.libsvm
    - bob.learn.mlp
    - bob.learn.activation
    - bob.learn.em
    - bob.measure
    - bob.sp
    - bob.ip.base
    - bob.ip.color
    - bob.ip.draw
    - bob.ip.gabor
    - bob.measure
    - bob.db.base
    - bob.db.atnt
    - bob.learn.boosting
    - bob.ip.facedetect
    - bob.ip.flandmark
    - bob.io.video
    - matplotlib {{ matplotlib }}
    - six {{ six }}
    - scipy {{ scipy }}
    - scikit-learn {{ scikit_learn }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('scikit-learn', min_pin='x.x') }}

test:
  imports:
    - {{ name }}
  commands:
    - bob pad --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - gridtk

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: A framework for executing the chain of presentation attack detection (PAD) experiments
  license_family: GPL
