{% set data = load_file_data(RECIPE_DIR + '/../pyproject.toml') %}
{% set name = data['project']['name'] %}

package:
  name: {{ name }}
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  noarch: python
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - "{{ PYTHON }} -m pip install {{ SRC_DIR }} -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - clapp
    - bob.extension
    - bob.io.base
    - bob.pipelines
    - bob.measure
    - bob.bio.base
    - click {{ click }}
    - click-plugins {{ click_plugins }}
    - dask {{ dask }}
    - matplotlib {{ matplotlib }}
    - numpy {{ numpy }}
    - scikit-learn {{ scikit_learn }}
    - scipy {{ scipy }}
    - sqlalchemy {{ sqlalchemy }}
    - tabulate {{ tabulate }}
  run:
    - python
    - setuptools
    - clapp
    - bob.extension
    - bob.io.base
    - bob.pipelines
    - bob.measure
    - bob.bio.base
    - {{ pin_compatible('click') }}
    - {{ pin_compatible('click-plugins') }}
    - {{ pin_compatible('dask') }}
    - {{ pin_compatible('matplotlib') }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scikit-learn') }}
    - {{ pin_compatible('scipy') }}
    - {{ pin_compatible('sqlalchemy') }}
    - {{ pin_compatible('tabulate') }}

test:
  imports:
    - {{ name.replace('-','_') }}
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: {{ data['project']['urls']['homepage'] }}
  summary: {{ data['project']['description'] }}
  license: {{ data['project']['license']['text'] }}
  license_family: GPL
